export type RuleStatus = "draft" | "active" | "gray" | "inactive";
export type RuleType = "process" | "validation" | "routing";
export type SynonymStatus = "active" | "inactive";
export type ReviewStatus = "pending_review" | "approved" | "rejected";
export type TenantStatus = "active" | "inactive" | "expired";
export type TenantIsolationType = "shared_rls" | "physical" | "schema";
export type SessionStatus = "normal" | "timeout" | "logout";

export interface AuthTokens {
  accessToken: string;
  refreshToken: string;
}

export interface LoginPayload {
  username: string;
  password: string;
  tenantCode: string;
}

export interface ListResponse<T> {
  items: T[];
}

export interface Rule {
  id: string;
  ruleCode: string;
  ruleName: string;
  ruleContent: string;
  ruleType: RuleType;
  parentRuleId: string | null;
  status: RuleStatus;
  version: number;
  grayRate: number;
  autoGenerated: boolean;
}

export interface RuleDraft {
  ruleCode: string;
  ruleName: string;
  ruleContent: string;
  ruleType: RuleType;
  parentRuleId: string;
  grayRate?: number;
}

export interface GeneratedRule {
  id: string;
  sourceClusterId: string;
  ruleContent: string;
  confidence: string;
  reviewStatus: ReviewStatus;
  reviewedBy: string | null;
  reviewComment: string | null;
  langflowRunId: string | null;
}

export interface Synonym {
  id: string;
  originWord: string;
  synonymWord: string;
  priority: number;
  status: SynonymStatus;
}

export interface SynonymDraft {
  originWord: string;
  synonymWord: string;
  priority?: number;
  status?: SynonymStatus;
}

export interface Tenant {
  id: string;
  tenantName: string;
  tenantCode: string;
  isolateType: TenantIsolationType;
  status: TenantStatus;
  expireTime: string | null;
  contactPerson: string | null;
  contactPhone: string | null;
}

export interface SessionRecord {
  id: string;
  sessionId: string;
  userIp: string;
  currentState: string;
  contextData: string;
  lastActiveTime: string | null;
  expireTime: string | null;
  sessionStatus: SessionStatus;
}

export const RULE_STATUS_META: Record<RuleStatus, { label: string; type: "info" | "success" | "warning" | "danger" }> = {
  draft: { label: "草稿", type: "info" },
  active: { label: "已生效", type: "success" },
  gray: { label: "灰度中", type: "warning" },
  inactive: { label: "已停用", type: "danger" }
};

export const RULE_TYPE_META: Record<RuleType, { label: string; type: "success" | "warning" | "info" }> = {
  process: { label: "流程规则", type: "success" },
  validation: { label: "校验规则", type: "warning" },
  routing: { label: "路由规则", type: "info" }
};

export const SYNONYM_STATUS_META: Record<SynonymStatus, { label: string; type: "success" | "danger" }> = {
  active: { label: "启用", type: "success" },
  inactive: { label: "停用", type: "danger" }
};

export const REVIEW_STATUS_META: Record<ReviewStatus, { label: string; type: "warning" | "success" | "danger" }> = {
  pending_review: { label: "待审核", type: "warning" },
  approved: { label: "已通过", type: "success" },
  rejected: { label: "已拒绝", type: "danger" }
};
