package com.xccdos.prolog.rule.web;

import com.xccdos.prolog.rule.domain.RulePrologEntity;

public record RuleResponse(
        String id,
        String ruleCode,
        String ruleName,
        String ruleContent,
        String ruleType,
        String parentRuleId,
        String status,
        int version,
        int grayRate,
        boolean autoGenerated
) {
    public static RuleResponse fromEntity(RulePrologEntity entity) {
        return new RuleResponse(
                String.valueOf(entity.getId()),
                entity.getRuleCode(),
                entity.getRuleName(),
                entity.getRuleContent(),
                entity.getRuleType().getApiValue(),
                entity.getParentId() == null ? null : String.valueOf(entity.getParentId()),
                entity.getStatus().getApiValue(),
                entity.getVersion(),
                entity.getGrayRate(),
                entity.getIsAutoGen() == 1
        );
    }
}
