import EvolutionReviewPage from "@/pages/EvolutionReviewPage.vue";
import { setAuthSession } from "@/lib/auth-session";
import { flushPromises } from "@vue/test-utils";
import { createTestRouter, mountWithPlugins } from "@/__tests__/helpers";

describe("EvolutionReviewPage", () => {
  it("calls approve endpoint from review list", async () => {
    setAuthSession({
      accessToken: "access-1",
      refreshToken: "refresh-1",
      tenantCode: "tenant-a",
      username: "tester"
    });

    vi.mocked(fetch)
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            items: [
              {
                id: "9",
                sourceClusterId: "88",
                ruleContent: "if vip then route premium",
                confidence: "0.91",
                reviewStatus: "pending_review",
                reviewedBy: null,
                reviewComment: null,
                langflowRunId: "lf-1"
              }
            ]
          }),
          { status: 200 }
        )
      )
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            id: "9",
            ruleCode: "AUTO-9",
            ruleName: "自动规则",
            ruleContent: "if vip then route premium",
            ruleType: "routing",
            parentRuleId: null,
            status: "active",
            version: 1,
            grayRate: 0,
            autoGenerated: true
          }),
          { status: 200 }
        )
      );

    const { pinia, router } = await createTestRouter("/evolution/review");
    const wrapper = mountWithPlugins(EvolutionReviewPage, router, pinia);
    await flushPromises();
    const approveButton = wrapper.findAll("button").find((button) => button.text().includes("通过"));
    await approveButton?.trigger("click");
    await flushPromises();

    expect(String(vi.mocked(fetch).mock.calls[1]?.[0])).toContain("/api/v1/evolution/generated-rules/9/approve");
  });
});
