import RulesPage from "@/pages/RulesPage.vue";
import { setAuthSession } from "@/lib/auth-session";
import { flushPromises } from "@vue/test-utils";
import { createTestRouter, mountWithPlugins } from "@/__tests__/helpers";

describe("RulesPage", () => {
  it("renders fetched rules and labels", async () => {
    setAuthSession({
      accessToken: "access-1",
      refreshToken: "refresh-1",
      tenantCode: "tenant-a",
      username: "tester"
    });

    vi.mocked(fetch).mockResolvedValueOnce(
      new Response(
        JSON.stringify({
          items: [
            {
              id: "1",
              ruleCode: "R-001",
              ruleName: "进线路由",
              ruleContent: "route(User, vip).",
              ruleType: "routing",
              parentRuleId: null,
              status: "gray",
              version: 4,
              grayRate: 25,
              autoGenerated: false
            }
          ]
        }),
        { status: 200 }
      )
    );

    const { pinia, router } = await createTestRouter("/rules");
    const wrapper = mountWithPlugins(RulesPage, router, pinia);
    await flushPromises();

    expect(wrapper.text()).toContain("进线路由");
    expect(wrapper.text()).toContain("灰度中");
    expect(wrapper.text()).toContain("路由规则");
  });
});
